"""Regenerate the homepage hero trajectories from a real curated dataset.

The homepage hero plots actual measurements rather than decorative artwork. This
script reads one dataset out of `_datasets/` (populated by `make ^_datasets-yaml`)
and writes normalized SVG coordinates to `_data/hero_trace.yaml`, which index.md
renders in Liquid.

The output is committed, so the site build stays pure Ruby -- CI has no Python.
Rerun this only to change the featured study or the plot geometry:

    python tools/make_hero_trace.py
"""

import math
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
# The study both site tutorials model, so the hero shows data a reader can follow
# straight through to a worked example.
DATASET = "woelfel2020virological"
# Stool rather than sputum: fecal shedding is what the wastewater-surveillance
# audience models, and its limit of quantification is the same 100 gc/mL.
ANALYTE = "stool"
SOURCE = ROOT / "_datasets" / f"{DATASET}.yaml"
DEST = ROOT / "_data" / "hero_trace.yaml"

# viewBox the hero SVG is drawn in
W, H = 1200.0, 420.0
# log10 concentration range mapped onto the vertical axis
LOG_MIN, LOG_MAX = 1.0, 10.0
# Limit of quantification for this study, in gc/mL
LOQ = 100.0
LOQ_LOG = math.log10(LOQ)
# How close to the limit a point must sit to be drawn as censored
CENSORED_MARGIN = 0.4
# Minimum measurements before a participant is worth drawing as a trajectory
MIN_POINTS = 4


def x_of(t, t_min, t_max):
    return (t - t_min) / (t_max - t_min) * W


def y_of(value):
    # Floored at the quantification limit, the convention for non-detects: a
    # result below it is plotted at the limit, not at whatever number the assay
    # returned. It also makes the dashed line a true floor for the plot.
    log = max(LOQ_LOG, min(LOG_MAX, math.log10(value)))
    return H - (log - LOG_MIN) / (LOG_MAX - LOG_MIN) * H


def polyline(points):
    """Straight segments between consecutive measurements.

    Deliberately not smoothed: a spline through these points would draw peaks and
    shoulders nobody measured, which is the opposite of what this repository is
    for. Every vertex here is an observation.
    """
    return " ".join(f"{x:.1f},{y:.1f}" for x, y in points)


def main():
    data = yaml.safe_load(SOURCE.read_text(encoding="utf-8"))

    series = []
    for participant in data["participants"]:
        measurements = [
            (m["time"], m["value"])
            for m in participant.get("measurements", [])
            if m.get("analyte") == ANALYTE and isinstance(m.get("value"), (int, float))
        ]
        if len(measurements) >= MIN_POINTS:
            series.append(sorted(measurements))

    if not series:
        raise SystemExit(f"no {ANALYTE} series with >= {MIN_POINTS} points in {DATASET}")

    times = [t for s in series for t, _ in s]
    t_min, t_max = min(times), max(times)

    traces = [
        {"points": polyline([(x_of(t, t_min, t_max), y_of(v)) for t, v in s])}
        for s in series
    ]

    # Every observation is drawn, so the vertices of each line are visible as the
    # measurements they are. Censored ones are split out: at or below the
    # quantification limit a result is "not detected", not zero -- the distinction
    # the package exists to handle correctly.
    dots, censored = [], []
    for s in series:
        for t, v in s:
            point = {"x": round(x_of(t, t_min, t_max), 1), "y": round(y_of(v), 1)}
            if math.log10(v) <= LOQ_LOG + CENSORED_MARGIN:
                censored.append(point)
            else:
                dots.append(point)

    payload = {
        "source": DATASET,
        "analyte": ANALYTE,
        "width": int(W),
        "height": int(H),
        "loq_y": round(H - (LOQ_LOG - LOG_MIN) / (LOG_MAX - LOG_MIN) * H, 1),
        "traces": traces,
        "dots": dots,
        "censored": censored,
    }

    DEST.write_text(
        f"# Generated by tools/make_hero_trace.py from {DATASET}. Do not edit by hand.\n"
        + yaml.safe_dump(payload, sort_keys=False, default_flow_style=False),
        encoding="utf-8",
    )
    print(
        f"{len(traces)} participants, {len(dots)} quantified points, "
        f"{len(censored)} censored -> {DEST}"
    )


if __name__ == "__main__":
    main()
